// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaC5VMP0USuJLNb5Xp8uvypsKS8puus4Y',
    appId: '1:144742239897:web:de20baad676f3018427208',
    messagingSenderId: '144742239897',
    projectId: 'brgy133-system',
    authDomain: 'brgy133-system.firebaseapp.com',
    storageBucket: 'brgy133-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqsCwqDMxkdd5uBtScgJOMBx9rd-UaBc',
    appId: '1:144742239897:android:cffe938c897e0211427208',
    messagingSenderId: '144742239897',
    projectId: 'brgy133-system',
    storageBucket: 'brgy133-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdO0jQvnifO5gpkDIE8TFQssXh-zhVA7M',
    appId: '1:144742239897:ios:d67f95d943028ff8427208',
    messagingSenderId: '144742239897',
    projectId: 'brgy133-system',
    storageBucket: 'brgy133-system.firebasestorage.app',
    iosBundleId: 'com.barangay133.flutterApp',
  );
}
